`pkg/client/service.go`: Read error message from `response.Body`.
Now we get the below:

```sh
--- FAIL: TestRun (0.41s)
    run_test.go:100: 200
    require.go:794:
        	Error Trace:	run_test.go:72
        	Error:      	Received unexpected error:
        	            	unexpected status code setting config 400, {"error":"credit_account: (identification: cannot be blank; scheme_name: cannot be blank.)."}
        	Test:       	TestRun
FAIL
FAIL	bitbucket.org/openbankingteam/conformance-suite/pkg/e2e	0.462s
```

---
REFAPP-708
As an Implementer, I need to enter creditor account information so that I can run payment tests.