Merged in feature/refapp_512_as_a_user_i_require_a_form_wh (pull request #91)
REFAPP-512: As a User, I require a form which POSTs global configuration data o the backend so that the suite can execute my tests

* cleanup and better error handling

    renames:
    * rename `serverUrl` to `serverURL`.
    * rename `appConfigJSONWithUrl` to `appConfigJSONWithURL`.

    `pkg/server/websocket_test.go`:
    * change test to use `require` instead of `assert`.

    `pkg/server/server_config_global_test.go`:
    * fix: `pkg/server/server_config_global_test.go:21:23: Error return value of `server.Shutdown` is not checked (errcheck)`
    * fix: `pkg/server/server_config_global_test.go:100:23: Error return value of `server.Shutdown` is not checked (errcheck)`
    * fix: `pkg/server/server_config_global_test.go:164:23: Error return value of `server.Shutdown` is not checked (errcheck)`

    `pkg/server/server_test.go`:
    * fix: `pkg/server/server_test.go:144:23: Error return value of `server.Shutdown` is not checked (errcheck)`
    * fix: `pkg/server/server_test.go:186:23: Error return value of `server.Shutdown` is not checked (errcheck)`
    * fix: `pkg/server/server_test.go:227:23: Error return value of `server.Shutdown` is not checked (errcheck)`
    ---
    REFAPP-512
    As a User, I require a form which POSTs global configuration data o the backend so that the suite can execute my tests.

* ui cleanup: use `<style scoped>` instead of just `<style>`.
    ---
    REFAPP-512
    As a User, I require a form which POSTs global configuration data o the backend so that the suite can execute my tests.

* WIP: form to post global configuration
    ---
    REFAPP-512
    As a User, I require a form which POSTs global configuration data o the backend so that the suite can execute my tests.

* form to post global configuration: vuex tests
    ---
    REFAPP-512
    As a User, I require a form which POSTs global configuration data o the backend so that the suite can execute my tests.

* form to post global configuration: code review points

    * "file name is not truncated when displaying so looks messy.": remove `align-items-start`.
    * "It’s a POST, I would expect the response to be 201?": make backend return `201` instead of `200`.
    * put handlers into separate file: `pkg/server/config_handlers.go`.
    * put tests into separate file: `pkg/server/config_handlers_test.go`.
    * misc cleanup to go code; 1. make `NullLogger` -> `nullLogger`, 2. require no error on shutdown.
    ---
    REFAPP-512
    As a User, I require a form which POSTs global configuration data o the backend so that the suite can execute my tests.

Approved-by: José Pinto <bluecor@gmail.com>
Approved-by: Glyn Jackson <me@glynjackson.org>